<?php 
$_config = Mage::helper('ewlayerednav/config');
$_maxVisible = $this->getMaxVisibleFilters();
?>
<?php if($this->canShowBlock()): ?>
<div class="block block-layered-nav ewlayerednav-layered-nav category-inner">
    <div class="block-title">
        <strong><span><?php echo $this->__('Shop By') ?></span></strong>
    </div>
    <div class="block-content">
        <?php if($this->canShowOptions()): ?>
            <h4 class="block-subtitle"><?php echo $this->__('Shopping Options') ?></h4>
            <?php if ($this->hasSelectedOptions() === true): ?>
            <div class="actions"><a href="<?php echo $this->getClearUrl() ?>" class="attr-clear-all"><?php echo $this->__('Clear All') ?></a></div>
            <?php endif; ?>
            <dl id="narrow-by-list">
            	<?php $_filterCount = 0; ?>
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                	<?php if ($this->canShowFilter($_filter) === true): ?>
                		<?php if ($_filter instanceof Extendware_EWLayeredNav_Block_Catalog_Layer_Filter_Attribute): ?>
                			<?php $_filterCount++; ?>
                		<?php endif; ?>
	                    <dt class="<?php echo $_filterCount > $_maxVisible ? 'attr-header attr-other' : 'attr-header'?>" style="<?php echo $_filterCount > $_maxVisible ? 'display:none;' : ''?>">
	                    	<?php if ($_filter->hasSelectedOptions() === true): ?>
	                    	<a id="<?php echo $_filter->getRequestVar(); ?>-clear" class="attr-clear btn-remove" href="<?php echo $_filter->getClearUrl() ?>" title="<?php echo $this->__('Remove This Item') ?>"><?php echo $this->__('Remove This Item') ?></a>
	                    	<?php endif; ?>	
                			<?php echo $this->__($_filter->getName()) ?>
	                    </dt>
	                    <dd class="<?php echo $_filterCount > $_maxVisible ? 'attr-other' : ''?>" style="<?php echo $_filterCount > $_maxVisible ? 'display:none;' : ''?>"><?php echo $_filter->getHtml() ?></dd>
					<?php endif; ?>
                <?php endforeach; ?>
            </dl>
            <?php if ($_filterCount > $_maxVisible): ?>
				<dl id="attr-toggler">
					<dd><a href="javascript:void(0);"><?php echo $this->__('Show More Attributes'); ?></a></dd>
				</dl>
			<?php endif; ?>
			<?php if (Mage::helper('ewlayerednav')->isSearch()): ?>
			<input type="hidden" name="ewlayerednav-search-params" id="ewlayerednav-search-params" value="<?php echo $this->getSearchParamString(array(Mage_CatalogSearch_Helper_Data::QUERY_VAR_NAME)); ?>">
			<?php endif; ?>
            <input type="hidden" name="ewlayerednav-params" id="ewlayerednav-params" value="<?php echo $this->getParamString(); ?>">
			<input type="hidden" name="ewlayerednav-url" id="ewlayerednav-url" value="<?php echo $this->getUrlForAjax(); ?>">
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>