<ol class="attr-box <?php echo $this->_filter->getAttributeModel()->getAttributeCode(); ?>-attr">
<?php foreach ($this->getItems() as $_item): ?>
    <li>
        <a id="<?php echo $_item->getFilter()->getRequestVar() . '-' . $_item->getValueString()?>" href="<?php echo $this->htmlEscape($_item->getUrl()) ?>" class="attr-opt <?php if ($this->isSelected($_item)) echo 'price-attr-selected';?>"><?php echo $_item->getLabel() ?></a> (<?php echo $_item->getCount() ?>)
    </li>
<?php endforeach ?>
</ol>