<?php 
	$min = $this->_filter->getOrigMinPriceInt(); 
    $max = $this->_filter->getOrigMaxPriceInt(); 

    list($from, $to) = $this->_filter->getInputtedRange(); 
    $from = max($from, $min);
    $to = min($to, $max);
    
    if ($to < 0.01) $to = sprintf('%.02f', $max);
	$from = (float)$from;
    $to = (float)$to;
    
    $width = 170;
    $range = $max - $min;
    $firstOffset = (($from - $min)/$range)*$width;
    $secondOffset = (($to-$min)/ $range)*$width;
?>
<ol class="attribute-box <?php echo $this->_filter->getAttributeModel()->getAttributeCode(); ?>-attr">
    <li>
		<div id="price-slider">
			<div class="handle left" style="left:<?php echo (float)$firstOffset?>px"></div>
			<div class="handle right" style="left:<?php echo (float)$secondOffset?>px"></div>
		</div>
		<?php echo $this->__('Range:')?> <?php echo $this->getSymbol()?><span id="range-from"><?php echo $from?></span> - <?php echo $this->getSymbol()?><span id="range-to"><?php echo $to?></span>
		<script type="text/javascript">
			<?php if (Mage::app()->getRequest()->isXmlHttpRequest() === false): ?>
			Event.observe(document, 'ewlayerednav:loaded', function(){
				Event.stopObserving(document, 'ewlayerednav:loaded');
				ewlayerednav.initSlider(<?php echo $width; ?>, <?php echo $firstOffset; ?>, <?php echo $secondOffset; ?>, <?php echo $min; ?>, <?php echo $max; ?>);
			});
			<?php else: ?>
			ewlayerednav.initSlider(<?php echo $width; ?>, <?php echo $firstOffset; ?>, <?php echo $secondOffset; ?>, <?php echo $min; ?>, <?php echo $max; ?>);
			<?php endif; ?>
		</script>
	</li>
</ol>
