<input 
    id='trustpilot_trustbox_trustpilot_trustbox_group_trustpilot_trustpilot_trustbox_xpath' 
    name='groups[trustpilot_trustbox_group][fields][trustpilot_trustbox_xpath][value]' 
    value='<?php echo $this->getXPathValue() ?>' 
    type='hidden'
/>
<div id="preview-container">
    <script src="<?php echo $this->getPreviewUrl(); ?>js/preview.js"></script>
    <iframe
        src="<?php echo $this->getUrl(); ?>"
        data-trustpilot_trustbox_homepage="<?php echo $this->getUrl('trustpilot_trustbox_homepage'); ?>"
        data-trustpilot_trustbox_category="<?php echo $this->getUrl('trustpilot_trustbox_category'); ?>"
        data-trustpilot_trustbox_product="<?php echo $this->getUrl('trustpilot_trustbox_product'); ?>"
        id="trustbox_preview_frame"
        onload="TrustpilotPreview.init('<?php echo $this->getIframeCssUrl(); ?>');"
        frameborder="0"
        width="100%"
        height="800">
    </iframe>
    <div id="preview-spinner">
        <div class="load-spinner">
            <div class="one"></div>
            <div class="two"></div>
            <div class="three"></div>
            <div class="four"></div>
            <div class="five"></div>
        </div>
        <div class="ls-backdrop"></div>
    </div>
</div>

<div id="preview-message">
    <div class="trustbox-message-box shake-element">
        <div class="fa fa-warning warning-icon"></div>
        <div class="trustbox-message-text">
            <?php echo $this->__('You will not be able to setup TrustBox as your current browser do not support modern HTML features'); ?>
        </div>
    </div>
</div>

<script>
    if (bowser && bowser.msie && bowser.version <= 11) {
        document.getElementById('preview-container').style.display = 'none';
        document.getElementById('preview-message').style.display = 'block';
    } else {
        document.getElementById('preview-container').style.display = 'block';
        document.getElementById('preview-message').style.display = 'none';       
    }
</script>
