<?php
/**
 * Layered Navigation Pro
 *
 * @category:    AdjustWare
 * @package:     AdjustWare_Nav
 * @version      2.5.11
 * @license:     HxObcXe62uQsQGs98TzFPLxwiM3aCakojlW7nJdmvI
 * @copyright:   Copyright (c) 2014 AITOC, Inc. (http://www.aitoc.com)
 */
if(Mage::helper('adjnav')->isModuleEnabled('Aitoc_Aitmanufacturers')):?>
<script type="text/javascript">
var currentShopByAttribute = "<?php echo Mage::registry('shopby_attribute');?>";
var currentShopByAttributeValue = "<?php echo Mage::getSingleton('core/session')->getAitocManufacturersCurrentManufacturerId();?>";
</script>
<?php endif;?>