<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Autorelated
 * @version    2.4.8
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
$abstractBlock = $this->helper('awautorelated')->getAbstractProductBlock();
$collection = $this->getCollection();

if ($this->getPosition() == AW_Autorelated_Model_Source_Position::INSTEAD_NATIVE_RELATED_BLOCK) {

    $this->iterateBlock();

    if ($collection && $collection->getSize()) {
        $this->markAsShowed();
    } elseif ($this->showNativeBlock()) {
        echo $this->getParent()->getChildHtml('catalog-product-related');
    }
}
?>
<?php if ($collection && $collection->getSize()) : ?>
<div class="related-items">
    <h2><?php echo $this->__('Related Items') ?></h2>
    <div class="inner-block">
        <div class="product-list">
            <ul class="awautorelated-grid-item">
            <?php foreach ($collection as $product) : ?>
                <li>
                    <a href="<?php echo $abstractBlock->getProductUrl($product) ?>"><img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(75) ?>" alt="<?php echo $this->htmlEscape($product->getName()) ?>" width="75" height="75" /></a>
                    <div class="itemname"><a href="<?php echo $abstractBlock->getProductUrl($product) ?>"><?php echo $this->htmlEscape($product->getName()) ?></a></div>
                    <?php echo $abstractBlock->getPriceHtml($product, true, '-related') ?>
                </li>
            <?php endforeach ?>
            </ul>
        </div>
    </div>
</div>
<?php endif;?>
