<?php if ($this->isEnabled()): ?>
<div class="shipping-calculator">
    <h3><?php echo $this->__('Ship to') ?></h3>
    <div class="input-group">
        <input type="text" id="estimate_postcode" name="estimate[postcode]" class="form-control input-text" value="<?php echo $this->htmlEscape($this->getFieldValue('postcode')) ?>" maxlength="12" placeholder="Enter Your Zip Code">
        <input type="hidden" id="estimate_country" name="estimate[country_id]" value="<?php echo $this->htmlEscape($this->getConfig()->getDefaultCountry())?>" />
        <span class="input-group-btn">
            <button type="button" class="btn btn-default btn-md" id="estimate-btn" onclick="estimateProductShipping()"><?php echo $this->__('Estimate') ?></button>
        </span>
    </div>
    <div id="shipping-estimate-results" style="display:none"></div>
</div>
<script type="text/javascript">
//<![CDATA[
function estimateProductShipping()
{
    var estimationUrl = '<?php echo $this->jsQuoteEscape($this->getEstimateUrl());?>';
    var items = $$(['.shipping-calculator input',
                    '.product-options input',
                    '.product-options select',
                    '.add-to-cart input']);
    var parameters = Form.serializeElements(items, true);
    $('shipping-estimate-results').hide();
    $('estimate-btn').update('<span class="spinner"><i class="fa fa-spinner fa-spin"></i></span> Loading');
    new Ajax.Updater('shipping-estimate-results', estimationUrl, {
        parameters: parameters,
        onComplete: function() {
            $('shipping-estimate-results').show();
            var results = $('shipping-estimate-results').innerHTML;
            if (results.indexOf('ewpagecache') > 0 && results.length < 90) {
                $('shipping-estimate-results').update('<div class="no-result">Please call for a quote.</div>');
            }
            $('estimate-btn').update('<?php echo $this->__('Estimate') ?>');
        }
    });
}
//]]>
</script>
<?php endif;?>
