<?php
$notice = $this->getNotice();
$config = $this->getConfig();
$helper = Mage::helper('le_cartmigration');
$import = $config['import'];
$add_options = $config['add_option'];
$entities = "";
if($import){
    foreach($import as $key => $value){
        if($value == true){
            $entities .= ' - '.ucfirst($key).'<br />';
        }
    }
}
?>
<form action="" method="post" id="le-form-resume">
<div id="lecm-resume">
    <h1 id="resume-header"><?php echo $this->__("Incompleted Last Migration"); ?></h1>
    <div>Due to some reason, your last migration hasn't been completed yet. Please check the blow information and resume if you wish.</div>
    <br />
    <div>
        <div class="lecm-title"><?php echo $this->__("Source Cart"); ?></div>
        <div class="le-form-fields">
            <div class="resume-label">
                <span><label><?php echo  $this->__('Cart Type'); ?></label></span>
            </div>
            <div class="resume-value">
                <span><?php echo $helper->getCmsTypeByValue($config['cart_type']); ?></span>
            </div>
        </div>
        <div class="le-form-fields">
            <div class="resume-label">
                <span><label><?php echo  $this->__('Cart Url'); ?></label></span>
            </div>
            <div class="resume-value">
                <span><?php echo $config['site_url']; ?></span>
            </div>
        </div>
        <div class="lecm-title"><?php echo $this->__("Languages Mapping"); ?></div>
        <?php foreach($config['language_data'] as $language){ ?>
            <div class="le-form-fields">
                <div class="resume-label">
                    <span><label><?php echo  $language['label']?></label></span>
                </div>
                <div class="resume-char"></div>
                <div class="resume-value">
                    <span><?php echo $helper->getWebsiteByValue($config['store_ids'][$language['value']]); ?></span>
                </div>
            </div>
        <?php } ?>
        <div class="lecm-title"><?php echo $this->__("Root Category"); ?></div>
        <div class="le-form-fields">
            <div class="resume-label">
                <span><label><?php echo $this->__("Root Category:"); ?></label></span>
            </div>
            <div class="resume-char"></div>
            <div class="resume-value">
                <span><?php echo $helper->getCategoryByValue($config['root_category_id']); ?></span>
            </div>
        </div>
        <div class="lecm-title"><?php echo $this->__("Product Attribute Set"); ?></div>
        <div class="le-form-fields">
            <div class="resume-label">
                <span><label><?php echo $this->__("Attribute Set:"); ?></label></span>
            </div>
            <div class="resume-char"></div>
            <div class="resume-value">
                <span><?php echo $helper->getAttributeSetByValue($config['attribute_set_id']); ?></span>
            </div>
        </div>
        <div class="lecm-title"><?php echo $this->__("Currencies Mapping"); ?></div>
        <?php foreach($config['currency_data'] as $currency){ ?>
            <div class="le-form-fields">
                <div class="resume-label">
                    <span><label><?php echo $currency['label']; ?></label></span>
                </div>
                <div class="resume-char"></div>
                <div class="resume-value">
                    <span><?php echo $helper->getCurrencyByValue($config['currencies'][$currency['value']]); ?></span>
                </div>
            </div>
        <?php } ?>
        <div class="lecm-title"><?php echo $this->__("Orders Status Mapping"); ?></div>
        <?php foreach($config['order_status_data'] as $status){?>
            <div class="le-form-fields">
                <div class="resume-label">
                    <span><label><?php echo $status['label']; ?></label></span>
                </div>
                <div class="resume-char"></div>
                <div class="resume-value">
                    <span><?php echo $helper->getOrderStatusByValue($config['order_status'][$status['value']]); ?></span>
                </div>
            </div>
        <?php }?>
        <div class="lecm-title"><?php echo $this->__("Entities to Migrate"); ?></div>
        <div class="le-form-fields">
            <div class="resume-value">
                <span><?php echo $entities; ?></span>
            </div>
        </div>
        <?php if($add_options['clear_data'] || $add_options['seo_url'] || $add_options['img_des']){?>
            <div class="lecm-title"><?php echo $this->__("Additional Options"); ?></div>
            <div class="le-form-fields">
                <div class="resume-value">
                    <?php if($add_options['clear_data']){?><p> - <?php echo $this->__("Clear current data on Target Store before Migration"); ?></p><?php } ?>
                    <?php if($add_options['seo_url']){?><p> - <?php echo $this->__("Migrate categories and products SEO URLs"); ?></p><?php } ?>
                    <?php if($add_options['img_des']){?><p> - <?php echo $this->__("Transfer images in product descriptions to your site"); ?></p><?php } ?>
                    <?php if($add_options['cus_id']){?><p> - <?php echo $this->__("Preserve Customer IDs on Target Store"); ?></p><?php } ?>
                    <?php if($add_options['ord_id']){?><p> - <?php echo $this->__("Preserve Order IDs on Target Store"); ?></p><?php } ?>
                    <?php if($add_options['stock']){?><p> - <?php echo $this->__("Ignore stock management for products with quantity = 0"); ?></p><?php } ?>
                </div>
            </div>
        <?php } ?>

    </div>
    <div>
        <div class="lecm-title"><?php echo $this->__("Previous Process"); ?></div>
        <div class="resume-value">
            <?php
            if($import){
                foreach($import as $key => $value){
                    if($value == true){ ?>
                        <p> - <?php echo $notice[$key]['imported_count'].'/'.$notice[$key]['total_count'].' '.$key.' completed, '.$notice[$key]['error_count'].' errors' ?><?php if($this->showIconSuccess($notice[$key])){echo '<span class="success-icon" style="display: inline-block;margin-left: 0.5em;"></span>';}?></p>
                    <?php }
                }
            }
            ?>
        </div>
        <div class="lecm-title"><?php echo $this->__("Do you want to resume last migration?"); ?></div>
        <input type="hidden" name="action" value="clear">
        <input type="hidden" name="is_running" value="yes"/>
        <div class="le-submit">
            <div id="le-loading-resume"><?php echo $this->__('Connecting ... ')?></div>
            <div id="lecm-resume-submit" class="lecm-submit">
                <a href="javascript:void(0)" class="le-button"><?php echo $this->__('Resume') ?></a>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>
</form>