<?php
$config = $this->getConfig();
$import = @$config['import'];
$add_options = @$config['add_option'];
?>
<h1 class="header_title">Configuration</h1>
<form action="" method="post" id="le-form-step2">
    <input type="hidden" name="action" value="config">

    <div class="le-container">
        <h1><?php echo $this->__("Root Category"); ?></h1>
        <div class="section_guide">
            Choose a Category to put migrated categories from Source Cart into.
        </div>
        <div class="le-form-fields">
            <div class="label-fields">
                <p>
                    <label>
                        <?php echo $this->__("Root Category:"); ?>
                        <span class="required">*</span>
                    </label>
                </p>
            </div>
            <div class="input-fields">
                <p>
                    <select id="root_category_id" name="root_category_id" class="required-entry input-text">
                        <?php echo $this->getCategoriesOption(@$config['root_category_id']);?>
                    </select>
                </p>
            </div>
        </div>

    </div>
    <div class="le-container">
        <h1><?php echo $this->__("Product Attribute Set"); ?></h1>
        <div class="section_guide">
            Choose an appropriate Product Attribute Set or just leave it Default.
        </div>
        <div class="le-form-fields">
            <div class="label-fields">
                <p>
                    <label>
                        <?php echo $this->__("Attribute Set:"); ?>
                        <span class="required">*</span>
                    </label>
                </p>
            </div>
            <div class="input-fields">
                <p>
                    <select id="attribute_set_id" name="attribute_set_id" class="required-entry input-text">
                        <?php echo $this->getAttributesOption(@$config['attribute_set_id']);?>
                    </select>
                </p>
            </div>
        </div>

    </div>
    <div class="le-container" id="lecm-lang-dup">
        <h1><?php echo $this->__("Languages Mapping"); ?></h1>
        <div class="section_guide">
            If your Source Cart is multilingual, corresponding languages ( or storeviews) should be available
            in Target Magento Store. You may need to create additional languages in Magento Store to avoid data loss.
        </div>
        <?php
        $languages = $this->getLanguageData();
        if($languages){
            foreach($languages as $language){
                ?>
                <div class="label-fields mapping">
                    <p><label><?php echo $language['label']; ?></label></p>
                </div>
                <div class="input-fields">
                    <p>
                        <select name="store_ids[<?php echo $language['value'];?>]" class="input-text">
                            <?php echo $this->getStoresOption(@$config['store_ids'][@$language['value']]);?>
                        </select>
                    </p>
                </div>
            <?php
            }
        }
        ?>
        <div class="label-fields">
            <p><label></label></p>
        </div>
        <div class="input-fields">
            <p>
            <div class="lecm-error validation-advice"><?php echo $this->__('Can not be the same Store View.'); ?></div>
            </p>
        </div>

    </div>
    <div class="le-container">
        <h1><?php echo $this->__("Currencies Mapping"); ?></h1>
        <div class="section_guide">
            Please assign Source Cart currencies to proper Target Magento Store currencies. Creating currencies
            in Target Magento Store may be needed.
        </div>
        <?php
            $currencies = $this->getCurrencyData();
            if($currencies){
                foreach($currencies as $currency){
                ?>
                    <div class="label-fields mapping">
                        <p><label><?php echo $currency['label']; ?></label></p>
                    </div>
                    <div class="input-fields">
                        <p>
                            <select name="currencies[<?php echo $currency['value'];?>]" class="input-text">
                                <?php echo $this->getCurrenciesOption(@$config['currencies'][@$currency['value']]);?>
                            </select>
                        </p>
                    </div>
                <?php
                }
            }
        ?>
    </div>
    <div class="le-container">
        <h1><?php echo $this->__("Orders Status Mapping"); ?></h1>
        <div class="section_guide">
            Please assign Source Cart order statuses to proper Target Magento Store order statuses.
            Creating additional order statues in Target Magento Store may be needed.
        </div>
        <?php
            $orderStatus = $this->getOrderStatusData();
            if($orderStatus){
                foreach($orderStatus as $status){
                ?>
                    <div class="label-fields mapping">
                        <p><label><?php echo $status['label']; ?></label></p>
                    </div>
                    <div class="input-fields">
                        <p>
                            <select name="order_status[<?php echo $status['value'];?>]" class="input-text">
                                <?php echo $this->getOrderStatusOption(@$config['order_status'][@$status['value']]);?>
                            </select>
                        </p>
                    </div>
                <?php
                }
            }
        ?>
    </div>

    <div class="le-input-fields le-container" id="input-fields-select">
        <h1><?php echo $this->__("Entities to Migrate"); ?></h1>
        <div class="section_guide">
            Select entities to migrate.
        </div>
        <div class="le-select-all">
            <input type="checkbox" title="" id="select-all" class="checkbox"/>
            <label class="le-select-checkbox"><?php echo $this->__("Select All"); ?></label>
        </div>
        <div id="le-list-product" class="lv0">
            <div class="le-select-cat">
                <input type="checkbox" name="products" id="select-products" class="checkbox lv1" <?php if($import['products']){echo "checked='checked'";}?> />
                <label class="le-select-checkbox"><?php echo $this->__("Products"); ?></label>
            </div>
            <ul class="le-list-select">
                <li>
                    <input type="checkbox" name="reviews" id="reviews" class="checkbox lv2" <?php if($import['reviews']){echo "checked='checked'";}?> />
                    <label class="le-select-checkbox"><?php echo $this->__("Reviews"); ?></label>
                </li>
                <li>
                    <input type="checkbox" name="categories" id="product-categories" class="checkbox lv2" <?php if($import['categories']){echo "checked='checked'";}?>/>
                    <label class="le-select-checkbox"><?php echo $this->__("Product Categories"); ?></label>
                </li>
                <li>
                    <input type="checkbox" name="manufacturers" id="manufacturers" class="checkbox lv2" <?php if($import['manufacturers']){echo 'checked="checked"';}?>/>
                    <label class="le-select-checkbox"><?php echo $this->__("Manufacturers"); ?></label>
                </li>
                <li>
                    <input type="checkbox" name="taxes" id="taxes" class="checkbox lv2" <?php if($import['taxes']){echo 'checked="checked"';}?>/>
                    <label class="le-select-checkbox"><?php echo $this->__("Taxes"); ?></label>
                </li>
            </ul>
        </div>
        <div id="le-list-customers" class="lv0">
            <div class="le-select-cat">
                <input type="checkbox" name="customers" id="customers" class="checkbox lv1" <?php if($import['customers']){echo 'checked="checked"';}?>/>
                <label class="le-select-checkbox"><?php echo $this->__("Customers"); ?></label>
            </div>
        </div>
        <div class="lv0">
            <ul class="le-select-cat">
                <li>
                    <input type="checkbox" name="orders" id="orders" class="checkbox lv1" <?php if($import['orders']){echo 'checked="checked"';}?>/>
                    <label class="le-select-checkbox"><?php echo $this->__("Orders"); ?></label>
                </li>
            </ul>
        </div>
    </div>
    <div class="le-error validation-advice"><?php echo $this->__('You must select at least one entity!') ?></div>
    <div class="clear"></div>

    <div class="input-fields le-additional le-container">
        <h1><?php echo $this->__("Additional Options"); ?></h1>
        <ul class="le-list-select">
            <li>
                <input type="checkbox" name="add_new" class="checkbox" <?php if(isset($add_options) && $add_options['add_new']){echo 'checked="checked"';}?>/>
                <label class="le-select-checkbox"><?php echo $this->__("Migrate recent data (adds new entities only)"); ?></label>
            </li>
            <li>
                <input type="checkbox" name="clear_data" class="checkbox" <?php if(isset($add_options) && $add_options['clear_data']){echo 'checked="checked"';}?>/>
                <label class="le-select-checkbox"><?php echo $this->__("Clear current data on Target Store before Migration"); ?></label>
            </li>
            <li>
                <input type="checkbox" name="img_des" class="checkbox" <?php if(isset($add_options) && $add_options['img_des']){echo 'checked="checked"';}?>/>
                <label class="le-select-checkbox"><?php echo $this->__("Transfer images from Product descriptions to Target Store"); ?></label>
            </li>
            <li>
                <input type="checkbox" name="cus_id" class="checkbox" <?php if(isset($add_options) && $add_options['cus_id']){echo 'checked="checked"';}?>/>
                <label class="le-select-checkbox"><?php echo $this->__("Preserve Customer IDs on Target Store"); ?></label>
            </li>
            <li>
                <input type="checkbox" name="ord_id" class="checkbox" <?php if(isset($add_options) && $add_options['ord_id']){echo 'checked="checked"';}?>/>
                <label class="le-select-checkbox"><?php echo $this->__("Preserve Order IDs on Target Store"); ?></label>
            </li>
            <li>
                <input type="checkbox" name="stock" class="checkbox" <?php if(isset($add_options) && $add_options['stock']){echo 'checked="checked"';}?>/>
                <label class="le-select-checkbox"><?php echo $this->__("Ignore stock management for products with quantity = 0"); ?></label>
            </li>
            <li>
                <input type="checkbox" id="choose-seo" name="seo_url" class="checkbox" <?php if(isset($add_options) && $add_options['seo_url']){echo 'checked="checked"';}?>/>
                <label class="le-select-checkbox"><?php echo $this->__("Migrate categories and products SEO URLs"); ?></label>
            </li>
            <div id="seo_plugin" class="le-container hidden">
                <div class="label-fields mapping">
                    <p><label><?php echo $this->__("Choose Plugin Seo In Source Cart"); ?></label></p>
                </div>
                <div class="input-fields">
                    <p>
                        <select name="seo_plugin">
                        <?php
                        if(isset($config['cart_type'])){
                            $seo_plugin = Mage::helper('le_cartmigration')->getSeoPlugin($config['cart_type']);
                            foreach($seo_plugin as $plugin){ ?>
                                <option value="<?php echo @$plugin['value']?>" <?php if(@$config['seo_plugin'] == @$plugin['value']){echo 'selected="selected"';}?>><?php echo @$plugin['label'];?></option>
                        <?php } }?>
                        </select>
                    </p>
                </div>
            </div>
        </ul>
    </div>
    <div class="clear"></div>
    <div class="le-submit">
        <div id="le-loading-step2"><?php echo $this->__('Preparing ...')?></div>
        <div id="lecm-form2-submit" class="lecm-submit">
            <a href="javascript:void(0)" class="le-button"><?php echo $this->__('Next') ?> &raquo;</a>
        </div>
    </div>
    <div id="lecm-back-step1" class="lecm-submit">
        <a href="javascript:void(0)" class="">&laquo; <?php echo $this->__('Back to previous Step') ?></a>
    </div>
</form>