<?php
$config = $this->getConfig();
$helper = Mage::helper('le_cartmigration');
$import = $config['import'];
$add_options = $config['add_option'];
$entities = "";
if($import){
    foreach($import as $key => $value){
        if($value == true){
            $entities .= ' - '.ucfirst($key).'<br />';
        }
    }
}
?>
<h1 class="header_title">Confirmation</h1>
<h1><?php echo $this->__("Source Cart"); ?></h1>
<div class="le-form-fields">
    <div class="label-fields">
        <p><label><?php echo  $this->__("Cart Type:"); ?></label></p>
    </div>
    <div class="input-fields">
        <p><?php echo $helper->getCmsTypeByValue($config['cart_type']); ?></p>
    </div>
</div>
<div class="le-form-fields">
    <div class="label-fields">
        <p><label><?php echo  $this->__("Cart Url:"); ?></label></p>
    </div>
    <div class="input-fields">
        <p><?php echo $config['site_url']; ?></p>
    </div>
</div>

<h1><?php echo $this->__("Languages Mapping"); ?></h1>
<?php foreach($config['language_data'] as $language){ ?>
    <div class="le-form-fields">
        <div class="label-fields">
            <p><label><?php echo  $language['label']?></label></p>
        </div>
        <div class="input-fields">
            <p><?php echo $helper->getWebsiteByValue($config['store_ids'][$language['value']]); ?></p>
        </div>
    </div>
<?php } ?>
<h1><?php echo $this->__("Root Category"); ?></h1>
<div class="le-form-fields">
    <div class="label-fields">
        <p><label><?php echo $this->__("Root Category:"); ?></label></p>
    </div>
    <div class="input-fields">
        <p><?php echo $helper->getCategoryByValue($config['root_category_id']); ?></p>
    </div>
</div>
<h1><?php echo $this->__("Product Attribute Set"); ?></h1>
<div class="le-form-fields">
    <div class="label-fields">
        <p><label><?php echo $this->__("Attribute Set:"); ?></label></p>
    </div>
    <div class="input-fields">
        <p><?php echo $helper->getAttributeSetByValue($config['attribute_set_id']); ?></p>
    </div>
</div>
<h1><?php echo $this->__("Currencies Mapping"); ?></h1>
<?php foreach($config['currency_data'] as $currency){ ?>
    <div class="le-form-fields">
        <div class="label-fields">
            <p><label><?php echo $currency['label']; ?></label></p>
        </div>
        <div class="input-fields">
            <p><?php echo $helper->getCurrencyByValue($config['currencies'][$currency['value']]); ?></p>
        </div>
    </div>
<?php } ?>
<h1><?php echo $this->__("Orders Status Mapping"); ?></h1>
<?php foreach($config['order_status_data'] as $status){?>
    <div class="le-form-fields">
        <div class="label-fields">
            <p><label><?php echo $status['label']; ?></label></p>
        </div>
        <div class="input-fields">
            <p><?php echo $helper->getOrderStatusByValue($config['order_status'][$status['value']]); ?></p>
        </div>
    </div>
<?php }?>
<h1><?php echo $this->__("Entities to Migrate"); ?></h1>
<div class="le-form-fields">
    <div class="input-fields">
        <p><?php echo $entities; ?></p>
    </div>
</div>
<?php if($add_options['clear_data'] || $add_options['seo_url'] || $add_options['img_des']){?>
<h1><?php echo $this->__("Additional Options"); ?></h1>
    <div class="le-form-fields">
        <div class="input-fields">
            <?php if($add_options['clear_data']){?><p> - <?php echo $this->__("Clear current data on Target Store before Migration"); ?></p><?php } ?>
            <?php if($add_options['seo_url']){?><p> - <?php echo $this->__("Migrate categories and products SEO URLs"); ?></p><?php } ?>
            <?php if($add_options['img_des']){?><p> - <?php echo $this->__("Transfer images from Product descriptions to Target Store"); ?></p><?php } ?>
            <?php if($add_options['cus_id']){?><p> - <?php echo $this->__("Preserve Customer IDs on Target Store"); ?></p><?php } ?>
            <?php if($add_options['ord_id']){?><p> - <?php echo $this->__("Preserve Order IDs on Target Store"); ?></p><?php } ?>
            <?php if($add_options['stock']){?><p> - <?php echo $this->__("Ignore stock management for products with quantity = 0"); ?></p><?php } ?>
        </div>
    </div>
    <?php } ?>

