<?php if ($this->checkDates() && $this->checkCountry() && $this->getProductCollection()->count()) : ?>
<input type="hidden" id="items-count-horizontal" name="items-count-horizontal"
       value="<?php echo $this->getProductsViewCount() ?>"/>
<input type="hidden" id="total-count-horizontal" name="total-count-horizontal"
       value="<?php echo $this->getProductCollection()->count() ?>"/>
<div class="product-view block" style="position: relative;margin-top: 5px">
    <div class="block-title">
        <strong>
            <span><?php echo $this->__($this->getBlockName()) ?></span></strong>
    </div>
    <a href="javascript:" id="btn-prev-horizontal" class="carousel-control triangle-left" rel="prev"></a>

    <div class="box-collateral box-up-sell" id="wrapper"
         style="position:relative;overflow: auto;margin: 0 auto;overflow-x: hidden;overflow-y: hidden;">
        <table class="products-grid secondary-wrapper" id="upsell-product-table-new">
            <tr>
                <?php foreach ($this->getProductCollection() as $_item) : ?>
                <td class="scroll-items">
                    <?php if (in_array('thumbnail', $this->getAttributes())) : ?>
                    <a href="<?php echo $_item->getProductUrl() ?>"
                       title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img
                        src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(125) ?>"
                        width="125" height="125" alt="<?php echo $this->htmlEscape($_item->getName()) ?>"/></a>
                    <?php endif; ?>
                    <?php if (in_array('name', $this->getAttributes())) : ?>
                    <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"
                                                title="<?php echo $this->htmlEscape($_item->getName()) ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                    </h3>
                    <?php endif; ?>
                    <?php if (in_array('price', $this->getAttributes())) : ?>
                    <?php echo $this->getPriceHtml($_item, true, '-upsell') ?>
                    <?php endif; ?>
                    <?php if (in_array('reviews', $this->getAttributes())) : ?>
                    <?php echo $this->getReviewsSummaryHtml($_item) ?>
                    <?php endif; ?>
                    <?php if (in_array('sku', $this->getAttributes())) : ?>
                    <div>SKU: <?php echo $_item->getSku(); ?></div>
                    <?php endif; ?>
                    <?php if (in_array('add_to_cart', $this->getAttributes())) : ?>
                    <div>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"
                                onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')">
                            <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    </div>
                    <?php endif; ?>
                </td>
                <?php endforeach; ?>
            </tr>
        </table>
    </div>
    <a href="javascript:" id="btn-next-horizontal" class="carousel-control triangle-right" rel="next"></a>
</div>
<script type="text/javascript">
    decorateTable('upsell-product-table-new');
    new ProductVerticalSlider('wrapper', 'td.scroll-items', $('btn-next-horizontal'), $('btn-prev-horizontal'), {visibleCount:$$('#items-count-horizontal')[0].value, mode:'horizontal', totalCount:$$('#total-count-horizontal')[0].value})
</script>
<?php endif ?>
