<?php if ($this->getAllowWriteReviewFlag()): ?>
<div class="review-form-add">
    <h2><?php echo $this->__('Write Your Own Review') ?></h2>
    <form action="<?php echo $this->getAction() ?>" method="post" id="review-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="review clearfix">
            <div class="rating-block">
                <?php if( $this->getRatings() && $this->getRatings()->getSize()): ?>
                <h4><?php echo $this->__('How do you rate this product?') ?> <em class="required">*</em></h4>
                <span id="input-message-box"></span>
                <table class="data-table" id="product-review-table">
                    <col />
                    <col width="1" />
                    <col width="1" />
                    <col width="1" />
                    <col width="1" />
                    <col width="1" />
                    <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th><span class="nobr"><?php echo $this->__('1 star') ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('2 stars') ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('3 stars') ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('4 stars') ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('5 stars') ?></span></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->getRatings() as $_rating): ?>
                        <tr>
                            <th><?php echo $this->escapeHtml($_rating->getRatingCode()) ?></th>
                        <?php foreach ($_rating->getOptions() as $_option): ?>
                            <td class="value"><input type="radio" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>" class="radio rating-radio" /> </td>
                        <?php endforeach; ?>
                        <div class="raiting-wrapper">   
                        <ul>
                            <li><i id="rate-1" class="fa fa-star rating-star" data-id="1"></i></li>
                            <li><i id="rate-2" class="fa fa-star rating-star" data-id="2"></i></li>
                            <li><i id="rate-3" class="fa fa-star rating-star" data-id="3"></i></li>
                            <li><i id="rate-4" class="fa fa-star rating-star" data-id="4"></i></li>
                            <li><i id="rate-5" class="fa fa-star rating-star" data-id="5"></i></li>
                            <li><span id="rate-description"></span></li>
                        </ul>
                         
                            
                        </div>
                       
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                <script type="text/javascript">decorateTable('product-review-table')</script>
                <?php endif; ?>
            </div>
            <div class="form-block">
                <ul class="form-list">
                    <li>
                        <label for="nickname_field" class="required"><em>*</em><?php echo $this->__('Nickname') ?></label>
                        <div class="input-box">
                            <input type="text" name="nickname" id="nickname_field" class="input-text required-entry" value="<?php echo $this->escapeHtml($data->getNickname()) ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="summary_field" class="required"><em>*</em><?php echo $this->__('Summary of Your Review') ?></label>
                        <div class="input-box">
                            <input type="text" name="title" id="summary_field" class="input-text required-entry" value="<?php echo $this->escapeHtml($data->getTitle()) ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="review_field" class="required"><em>*</em><?php echo $this->__('Review') ?></label>
                        <div class="input-box">
                            <textarea name="detail" id="review_field" cols="5" rows="3" class="required-entry"><?php echo $this->escapeHtml($data->getDetail()) ?></textarea>
                        </div>
                    </li>
                </ul>
                <div class="buttons-set">
                    <button type="submit" title="<?php echo $this->__('Submit Review') ?>" class="btn btn-black"><span><span><?php echo $this->__('Submit Review') ?></span></span></button>
                </div>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('review-form');
        Validation.addAllThese(
        [
               ['validate-rating', '<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Please select one of each of the ratings above')) ?>', function(v) {
                    var trs = $('product-review-table').select('tr');
                    var inputs;
                    var error = 1;

                    for( var j=0; j < trs.length; j++ ) {
                        var tr = trs[j];
                        if( j > 0 ) {
                            inputs = tr.select('input');

                            for( i in inputs ) {
                                if( inputs[i].checked == true ) {
                                    error = 0;
                                }
                            }

                            if( error == 1 ) {
                                return false;
                            } else {
                                error = 1;
                            }
                        }
                    }
                    return true;
                }]
        ]
        );
    //]]>
	
	jQuery('.rating-star').mouseover(function(){
		
		var rate=jQuery(this).data('id');
		var rated=jQuery('.rating-radio:checked').val();
		
		if(rate<rated) return;
		
		jQuery('.rating-star').removeClass('rated');
		for(i=1;i<=rate;i++){
			jQuery('#rate-'+i).addClass('rated');
		}
		
		if(!rated){
			var statement = "";
			switch(rate) {
				case 1:
					statement="Poor";
					break;
				case 2:
					statement="Bad";
					break;
				case 3:
					statement="Not Bad / Not Good";
					break;
				case 4:
					statement="Good";
					break;
				case 5:
					statement="Excellent";
					break;
				default:
					statement="";
			}
			jQuery('#rate-description').html(statement);
		}
	});
	
	jQuery('.rating-star').mouseout(function(){
		
		var rate=jQuery(this).data('id');
		var rated=jQuery('.rating-radio:checked').val();
		
		if(rate<rated) return;
		
		jQuery('.rating-star').removeClass('rated');
		for(i=1;i<=rated;i++){
			jQuery('#rate-'+i).addClass('rated');
		}
		
		if(!rated) jQuery('#rate-description').html('');
	});
	
	jQuery('.rating-star').click(function(){
		var rate=jQuery(this).data('id');
		jQuery('#Quality_'+rate).attr('checked', 'checked');
		jQuery('.rating-star').removeClass('rated');
		for(i=1;i<=rate;i++){
			jQuery('#rate-'+i).addClass('rated');
		}
		var statement = "";
		switch(rate) {
			case 1:
				statement="Poor";
				break;
			case 2:
				statement="Bad";
				break;
			case 3:
				statement="Not Bad / Not Good";
				break;
			case 4:
				statement="Good";
				break;
			case 5:
				statement="Excellent";
				break;
			default:
				statement="";
		}
		jQuery('#rate-description').html(statement);
	})
	
    </script>
</div>
<?php endif; ?>