<?php 
$_config = Mage::helper('ewlayerednav/config');
$_maxVisible = $this->getMaxVisibleOptions();
?>
<?php if ($_config->getMaxHeight() > 0): ?>
<ol class="attr-box std-attr-box <?php echo $this->_filter->getAttributeModel()->getAttributeCode(); ?>-attr" style="max-height: <?php echo $_config->getMaxHeight(); ?>px; overflow: auto">
<?php else: ?>
<ol class="attr-box std-attr-box <?php echo $this->_filter->getAttributeModel()->getAttributeCode(); ?>-attr">
<?php endif; ?>
<?php $_itemCount = 0; ?>
<?php foreach ($this->getItems() as $_item): ?>
	<?php if ($_item->getCount() > 0 or Mage::helper('ewlayerednav/config')->isEmptyFilterOptionsEnabled() === true): ?>
    <?php $_itemCount++; ?>
    <li class="<?php echo $_itemCount > $_maxVisible ? 'attr-opt-other' : ''?>" style="<?php echo $_itemCount > $_maxVisible ? 'display:none;' : ''?>">
        <a id="<?php echo $this->getHtmlId($_item); ?>" href="<?php echo $this->getItemUrl($_item); ?>" class="attr-opt <?php echo $this->isSelected($_item) ? 'selected' : ''?>"><?php echo $_item->getLabel() ?></a>
        (<?php echo $_item->getCount() ?>)
    </li>
    <?php endif; ?>
<?php endforeach; ?>
<?php if ($_itemCount > $_maxVisible): ?>
	<li class="attr-opt-toggler">
        <a href="javascript:void(0);"><?php echo $this->__('Show More'); ?></a>
    </li>
<?php endif; ?>
</ol>