<?php
    $_helper = $this->helper('catalog/output');
?>
<?php if ($this->checkDates() && $this->checkCountry() && $this->getProductCollection()->count()) : ?>
<div class="WebTexSoftFeaturedSlider">
<input type="hidden" class="items-count-horizontal" name="items-count-horizontal" value="<?php echo $this->getProductsViewCount() ?>"/>
<input type="hidden" class="total-count-horizontal" name="total-count-horizontal" value="<?php echo $this->getProductCollection()->count() ?>"/>
    <h4 class="text-left red mb5"><?php echo $this->__($this->getBlockName()) ?></h4>
    <div class="product-view block" style="position: relative;margin-top: 5px">
       <!-- <div class="block-title">
            <strong>
                <span></span></strong>
        </div>-->
        <a href="javascript:" class="carousel-control triangle-left btn-prev-horizontal" rel="prev"></a>
        <div class="box-collateral box-up-sell hor-wr" id="wrapper"
             style="position:relative;overflow: auto;margin: 0 auto;overflow-x: hidden;overflow-y: hidden;">
            <ul class="horizontal-slider secondary-wrapper" id="upsell-product-table-new">
                    <?php foreach ($this->getProductCollection() as $_item) : ?>
                    <li class="scroll-items">
                        <?php if ($this->isShowOption('thumbnail')) : ?>
                        <a href="<?php echo $_item->getProductUrl() ?>"
                           title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img
                            src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(125) ?>"
                            width="125" height="125" alt="<?php echo $this->htmlEscape($_item->getName()) ?>"/></a>
                        <?php endif; ?>
                        <?php if ($this->isShowOption('name')) : ?>
                        <div class="product-descr">
                        <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"
                                                    title="<?php echo $this->htmlEscape($_item->getName()) ?>"><?php echo $_helper->productAttribute($_item, $_item->getName() , 'name'); ?></a>
                        </h3>
                        <?php endif; ?>
                        <?php if ($this->isShowOption('price')) : ?>
                        <?php echo $this->getPriceHtml($_item, true, '-upsell') ?>
                        <?php endif; ?>
                        <?php if ($this->isShowOption('reviews')) : ?>
                        <?php echo $this->getReviewsSummaryHtml($_item) ?>
                        <?php endif; ?>
                        <?php if ($this->isShowOption('sku')) : ?>
                        <div>SKU: <?php echo $this->htmlEscape($_item->getSku()); ?></div>
                        <?php endif; ?>
                        <?php if ($this->isShowOption('add_to_cart') && $_item->isSaleable()) : ?>
                        <div>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"
                                    onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')">
                                <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        </div>
                        <?php endif; ?>
                        </div>
                    </li>
                    <?php endforeach; ?>

            </ul>
        </div>
    <a href="javascript:" class="carousel-control triangle-right btn-next-horizontal" rel="next"></a>
    </div>
</div>
<?php endif ?>
