<?php
    $_helper = $this->helper('catalog/output');
?>
<?php if ($this->checkDates() && $this->checkCountry() && $this->getProductCollection()->count()) : ?>
<div class="WebTexSoftFeaturedSlider">
    <div class="block block-related" style="position: relative;">
        <input type="hidden" class="items-count" name="items-count" value="<?php echo $this->getProductsViewCount() ?>"/>
        <a href="javascript:" class="carousel-control triangle-up btn-prev-vertical" rel="prev"></a>
        <div class="block-title">
            <strong><span><?php echo $this->__($this->getBlockName()) ?></span></strong>
        </div>
        <div class="block-content">
            <ol class="mini-products-list block-related-slider" style="list-style: none outside none; padding:0;">
                <?php foreach($this->getProductCollection() as $_item): ?>
                <li class="item slide-block" style = "padding: 7px 0;">
                    <div class="product">
                        <?php if ($this->isShowOption('thumbnail')) : ?>
                        <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(50) ?>" width="50" height="50" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                        <?php endif; ?>
                        <div class="product-details">
                            <?php if ($this->isShowOption('name')) : ?>
                            <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $_helper->productAttribute($_item, $_item->getName() , 'name'); ?></a></p>
                            <?php endif; ?>
                            <?php if ($this->isShowOption('price')) : ?>
                            <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                            <?php endif; ?>
                            <?php if ($this->isShowOption('reviews')) : ?>
                            <?php echo $this->getReviewsSummaryHtml($_item) ?>
                            <?php endif; ?>
                            <?php if ($this->isShowOption('sku')) : ?>
                            <div>SKU: <?php echo $this->htmlEscape($_item->getSku()); ?></div>
                            <?php endif; ?>
                            <?php if ($this->isShowOption('add_to_cart') && $_item->isSaleable()) : ?>
                            <div>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"
                                        onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')">
                                    <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </li>
                <?php endforeach ?>
            </ol>
            <script type="text/javascript">//decorateList('block-related-slider', 'none-recursive')</script>
        </div>
        <a href="javascript:" class="carousel-control triangle-down btn-next-vertical" rel="next"></a>
        <script type="text/javascript">
            //<![CDATA[
            $$('.slider-related-checkbox').each(function(elem){
                Event.observe(elem, 'click', addRelatedToProduct)
            });

            var relatedProductsCheckFlag = false;
            function selectAllRelated(txt){
                if (relatedProductsCheckFlag == false) {
                    $$('.slider-related-checkbox').each(function(elem){
                        elem.checked = true;
                    });
                    relatedProductsCheckFlag = true;
                    txt.innerHTML="<?php echo $this->__('unselect all') ?>";
                } else {
                    $$('.slider-related-checkbox').each(function(elem){
                        elem.checked = false;
                    });
                    relatedProductsCheckFlag = false;
                    txt.innerHTML="<?php echo $this->__('select all') ?>";
                }
                addRelatedToProduct();
            }

            function addRelatedToProduct(){
                var checkboxes = $$('.slider-related-checkbox');
                var values = [];
                for(var i=0;i<checkboxes.length;i++){
                    if(checkboxes[i].checked) values.push(checkboxes[i].value);
                }
                if($('related-products-field')){
                    $('related-products-field').value = values.join(',');
                }
            }


            //]]>
        </script>
    </div>
</div>
<?php endif ?>
