<?php
/**
 * @category    Trmmarketing
 * @package     Trmmarketing_PopupWidgets
 * @copyright   Copyright (c) 2014 TRM Marketing LLC
 * @license     http://www.trm-marketing.com/solutions/license/TRM-Marketing-Standard-License-Agreement.html
 */
 

$coupon = Mage::getModel('salesrule/coupon')->load($couponcode, 'code');

$newdate = new DateTime($coupon->getExpirationDate());
$storedate = new DateTime();
$storedate->setTimestamp(Mage::getModel('core/date')->timestamp(time()));
?>

<div id="popup-countdown-container">
<span id="promotionalPopupsCountdown" countdate="<?php echo $newdate->format('M d Y H:i:s'); ?>" storedate="<?php echo $storedate->format('M d Y H:i:s'); ?>"></span>
</div>