<?php
/**
 * @category    Trmmarketing
 * @package     Trmmarketing_PopupWidgets
 * @copyright   Copyright (c) 2014 TRM Marketing LLC
 * @license     http://www.trm-marketing.com/solutions/license/TRM-Marketing-Standard-License-Agreement.html
 */
?>


 
 <a id="promotionalpopupLink" style=" <?php echo $addcss; ?>" href="javascript:void(0);" rel="<?php echo $linkurl; ?>"><?php echo $linkbuttontext; ?></a>