<?php
/**
 * @category    Trmmarketing
 * @package     Trmmarketing_PopupWidgets
 * @copyright   Copyright (c) 2013-2015 TRM Marketing LLC
 * @license     http://www.trm-marketing.com/solutions/license/TRM-Marketing-Standard-License-Agreement.html
 */
?>

<?php $popupproduct = Mage::getModel('catalog/product')->load($popupproductid) ?>
<a href="<?php echo Mage::helper('checkout/cart')->getAddUrl($popupproduct) ?>" class="popupSimpleProductAddToCartLink"><?php echo $linkbuttontext; ?></a> 
