<?php
/**
 * @category    Trmmarketing
 * @package     Trmmarketing_PopupWidgets
 * @copyright   Copyright (c) 2014 TRM Marketing LLC
 * @license     http://www.trm-marketing.com/solutions/license/TRM-Marketing-Standard-License-Agreement.html
 */
?>

<div id="wistia_<?php echo $wistiaid; ?>" class="wistia_embed" style="width:<?php echo $videowidth; ?>px;height:<?php echo $videoheight; ?>px;" data-video-width="<?php echo $videowidth; ?>" data-video-height="<?php echo $videoheight; ?>">&nbsp;</div>
<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/E-v1.js"></script>
<script src="//fast.wistia.net/static/concat/E-v1-gridify,requireEmail-v1.js"></script>
<script src="//fast.wistia.net/static/concat/E-v1-gridify,socialbar-v1.js"></script>


<script>
wistiaEmbed = Wistia.embed("<?php echo $wistiaid; ?>", {
  version: "v1",
  videoWidth: <?php echo $videowidth; ?>,
  videoHeight: <?php echo $videoheight; ?>,
  volumeControl: true,
  controlsVisibleOnLoad: true,
});

Wistia.plugin.socialbar(wistiaEmbed, {
    version: "v1",
    buttons: "embed-email-twitter-facebook",
	showTweetCount:false,
	tweetText:"{video_name}",
	height:"25"
  });


Wistia.plugin.requireEmail(wistiaEmbed, {
    version: "v1",
	time:"end",
	provider:"hubspot",
	topText:"<?php echo $toptext; ?>",
    bottomText: "<?php echo $bottomtext; ?>"
	
});


<?php if ($videoautoplay == 1) { ?> wistiaEmbed.play(); <?php } ?> 

function stopVideo() {
        wistiaEmbed.pause();
      }
</script>

