<?php
/**
 * @category    Trmmarketing
 * @package     Trmmarketing_PopupWidgets
 * @copyright   Copyright (c) 2014 TRM Marketing LLC
 * @license     http://www.trm-marketing.com/solutions/license/TRM-Marketing-Standard-License-Agreement.html
 */
?>


 

    <div id="promotionalpopup-player" videoheight="<?php echo $videoheight; ?>" videowidth="<?php echo $videowidth; ?>" youtubeid="<?php echo $youtubeid; ?>" videoautoplay="<?php echo $videoautoplay; ?>"></div>
