<ol class="category-attr">
<?php foreach ($this->getItems() as $_item):?>
	<li>
		<?php if ($_item->getIsCurrent()): ?>
        	<span id="cat-<?php echo $_item->getValue()?>" class="cat-attr cat-current cat-pad<?php echo $_item->getLevel()?>"><?php echo $_item->getLabel() ?></span>
		<?php  else: ?>
			<a id="cat-<?php echo $_item->getValue()?>" href="<?php echo $this->htmlEscape($_item->getCategoryUrl()) ?>" class="cat-attr cat-pad<?php echo $_item->getLevel()?>"><?php echo $_item->getLabel()?></a> 
			<?php if($_item->getCount()): ?>  (<?php echo $_item->getCount() ?>) <?php endif ?>
		<?php endif ?>
	</li>
<?php endforeach ?>
</ol>