<?php
$brand = $this->getBrand();
if($brand):
    if($brand->getId()):
        ?>
        <div class="short_des">
            <a href="<?php echo $this->getUrl($brand->getUrlKey());?>">
                <?php
                if($brand->getThumbnailImage())
                {
                    //$path = 'brands' . DS . $brand->getId();
                    $path = 'brands' . DS . 'thumbnail'.DS.$brand->getId();
                    $imgSrc = Mage::helper('shopbybrand/image')->init($brand, $path)->resizeThumbnail(60, 40);
                    ?>
                    <img  src="<?php echo $imgSrc;?>" title="<?php echo $brand->getName();?>"/>
                <?php
                }
                ?>
                <div class="box1">
                    <?php echo $brand->getName();?>
                </div>
            </a>
            <?php /* edited by Esad <div class="s_description">
    <p>
        <?php
            $helper = Mage::helper('cms');
           $processor = $helper->getBlockTemplateProcessor();
            $html=$processor->filter($brand->getShortDescription());
            echo $html;
        ?>
    </p>
</div> */ ?>
        </div>
    <?php endif; endif; ?>
