<?php
$enabled = Mage::getStoreConfig('responsiveslideshow/responsiveslideshow_config/enabled');
$cur_store = Mage::app()->getStore()->getId();
if($enabled){
$bannerGroupID = (int)$this->getData('group_id');
$data = $this->getDataByGroupCode($bannerGroupID);
$bannerGroupData = $data['group_data'];

if($bannerGroupData){

$groupEnabled = $bannerGroupData->getStatus();
$storeId = $bannerGroupData->getStoreId();
$startDate = strtotime($bannerGroupData->getStartDate());
$endDate = strtotime($bannerGroupData->getEndDate());
$currentDate = strtotime(Mage::getModel('core/date')->date('m/d/Y H:i A'));

if($groupEnabled){
 $status =0;
if (($currentDate >= $startDate) && ($currentDate <= $endDate)){
  $status = 1;
}else  if (($currentDate <= $startDate) && ($currentDate >= $endDate)){
$status = 2;
}

if($status==0||$status==1){
if ($storeId == $cur_store || $storeId == 0 ) {

$bannerData = $data['responsiveslideshow_data'];
if($bannerGroupData->getCustomOdr()=="asc"){
sort($bannerData);
}else if($bannerGroupData->getCustomOdr()=="desc"){
rsort($bannerData);
}else if($bannerGroupData->getCustomOdr()=="rand"){
shuffle($bannerData);
}
$bannerdest = $bannerGroupData->getLinkTarget();
$transitionSettings = $bannerGroupData->getTransitionSettings();
$easingSettings = $bannerGroupData->getEasingSettings();
$showPaging = $bannerGroupData->getShowPaging();
$dynamicHeight = $bannerGroupData->getDynamicHeight();
$sliderWidth = ($bannerGroupData->getSliderWidth())? $bannerGroupData->getSliderWidth() :'640';
$sliderHeight = ($bannerGroupData->getSliderHeight())? $bannerGroupData->getSliderHeight() :'320';
$widthManagement = $bannerGroupData->getWidthManagement();
$pauseOnHover = ($bannerGroupData->getPauseOnHover()=='1')? 'true' :'false';
$touchSwipe = ($bannerGroupData->getTouchSwipe()=='1')? 'true' :'false';
$lightBox = $bannerGroupData->getLightbox();
$showProgressBar = $bannerGroupData->getShowProgressBar();

$showProgressBarColour = $bannerGroupData->getProgressBarColour();
$showProgressBarPosition = $bannerGroupData->getProgressBarPosition();

$showNav = $bannerGroupData->getShowNav();
$showContent = $bannerGroupData->getShowContent();
$sliderInterval = $bannerGroupData->getSliderInterval();
$sliderSpeed= $bannerGroupData->getSliderSpeed();

if($widthManagement=='full'){
$slide_width='max-width:100%';
}else if($widthManagement=='responsive') { $slide_width='max-width:'.$sliderWidth.'px'; 
}else if($widthManagement=='fixed'){ $slide_width = 'width:'.$sliderWidth.'px'; }

if($dynamicHeight=='1'){
$slide_height = 'max-height:'.$sliderHeight.'px'; 
}else{

$slide_height = 'max-height:'.$sliderHeight.'px'; 

}

      echo '<div class="wa_rs_relative_container" id="wa_rs_relative_container_'.$bannerGroupID.'" style="'.$slide_width.'; '.$slide_height.'; overflow:hidden; margin: auto;">';

      //Add some navigation
      if($showNav==1) {
      echo '<a  class="wa_rs_slide_nav wa_rs_prev" id="wa_rs_prev_'.$bannerGroupID.'"><img src="'.$this->getSkinUrl('weaveapps/images/wa_left.png').'" alt="prev"/></a>';
      echo '<a  class="wa_rs_slide_nav wa_rs_next" id="wa_rs_next_'.$bannerGroupID.'"><img src="'.$this->getSkinUrl('weaveapps/images/wa_right.png').'" alt="next" /></a>';
     }

     if($dynamicHeight==1){

   echo '<div class="wa-slideshow" id="wa-slideshow_'.$bannerGroupID.'" data-cycle-allow-wrap="true"
    data-cycle-fx='.$transitionSettings.'
    data-cycle-timeout='.$sliderInterval.'
    data-cycle-swipe='.$touchSwipe.'
    data-cycle-speed='.$sliderSpeed.'
    data-cycle-prev=#wa_rs_prev_'.$bannerGroupID.'
    data-cycle-next=#wa_rs_next_'.$bannerGroupID.'
    data-cycle-slides=">div"
    data-cycle-youtube=true
     data-cycle-auto-height=container
    data-cycle-pause-on-hover='.$pauseOnHover.'
    data-cycle-pager="#wa-rsp-pager-'.$bannerGroupID.'" >';

     }else{

  echo '<div class="wa-slideshow" id="wa-slideshow_'.$bannerGroupID.'" data-cycle-allow-wrap="true"
    data-cycle-fx='.$transitionSettings.'
    data-cycle-timeout='.$sliderInterval.'
    data-cycle-swipe='.$touchSwipe.'
    data-cycle-speed='.$sliderSpeed.'
    data-cycle-prev=#wa_rs_prev_'.$bannerGroupID.'
    data-cycle-next=#wa_rs_next_'.$bannerGroupID.'
    data-cycle-auto-height="'.$sliderWidth.':'.$sliderHeight.'"
    data-cycle-slides=">div"
    data-cycle-youtube=true
    data-cycle-pause-on-hover='.$pauseOnHover.'
    data-cycle-pager="#wa-rsp-pager-'.$bannerGroupID.'" >';
  }
$i = 0;


foreach ($bannerData as $banner) {

    $bannerType = $banner->getBannerType();
    $bannerPath = $banner->getFilename();
    $bannerTitle = $banner->getTitle();
    $bannerContent = $banner->getBannerContent();
    $bannerLink = $banner->getLink();
    $bannerdest= ($banner->getLinkTarget()==1)? $bannerdest="_self" : $bannerdest="_blank";

    $bgColour= $banner->getCaptionBgColour();
    $fontColour= $banner->getCaptionFontColour();
    $path = Mage::getBaseUrl('media');  
    $st1 =  $banner->getImage();
    $p1 = strpos($st1,'responsiveslideshow');
    $st2 = substr($st1,$p1+19);
    $p2 = strpos($st2,'"');
    $imag = substr($st2,0,$p2);

    if ($bannerType == 0){
        $i++;
        $v = "imgslid" . $i;
        echo '<div>'; 

if($bannerLink){ ?>      
             <a href="<?php echo (($bannerLink) ? $bannerLink : 'javascript:'); ?>"  <?php echo (($bannerLink)?' target="'.$bannerdest.'"':''); ?> title="<?php echo $bannerTitle; ?>"> <?php }  if($widthManagement=='fixed'){ ?>


                  <img  src="<?php echo $path.'weaveapps/responsiveslideshow/'.$imag; ?>" alt="<?php echo $bannerTitle; ?>" width="<?php echo $sliderWidth; ?>" height="<?php echo $sliderHeight; ?>" />



        <?php    }else { ?>

              <img  src="<?php echo $path.'weaveapps/responsiveslideshow/'.$imag; ?>" alt="<?php echo $bannerTitle; ?>" />


<?php } if ($bannerLink){ ?>
           </a> <?php } ?>
<?php
      $class = $banner->getCaptionPosition();
      echo '<div class="'.$class.'" style="color:'.$fontColour.' !important; background:'.$bgColour.' !important;"><div style="padding: 1em 2.7em;"><div>' ;
      echo '<h3 style="color:'.$fontColour.' !important; opacity: 1;">';
      echo $banner->getTitle();
      echo '</h3>';
      echo $banner->getCaption().'</div></div>';
      echo '</div>';
      echo '</div>';
    }else  {

      $videoLink = $banner->getVideoId();
      $videoHeight = $banner->getvideoHeight();
      $autoPlay = $banner->getautoPlay();
echo '<div style="height:100% !important;">';   

if ($bannerType == 1){ 

    if($widthManagement=='fixed'){

        echo '<iframe width="'.$sliderWidth.'" height="'.$sliderHeight.'"  src="//www.youtube.com/embed/'. $videoLink.'?autoplay='.$autoPlay.'" frameborder="0" allowfullscreen></iframe>'; 

    }else {


echo '<iframe width="100%" height="'.$sliderHeight.'"  src="//www.youtube.com/embed/'. $videoLink.'?autoplay='.$autoPlay.'" frameborder="0" allowfullscreen></iframe>'; 
    }
}else if ($bannerType == 2){ 



     if($widthManagement=='fixed'){



echo '<iframe src="//player.vimeo.com/video/'.$videoLink.'?title=0&amp;byline=0&amp;portrait=0&amp;autoplay='.$autoPlay.'" width="'.$sliderWidth.'" height="'.$sliderHeight.'" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>';



     }else{


echo '<iframe src="//player.vimeo.com/video/'.$videoLink.'?title=0&amp;byline=0&amp;portrait=0&amp;autoplay='.$autoPlay.'" width="100%"  height="'.$sliderHeight.'"frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>';

}

}
echo '</div>';
    }
  }

echo '</div>';

    //display progress bar  
    if($showProgressBar==1&&$sliderInterval>0){ 
  echo '<div style="background:'.$showProgressBarColour.'; '.$showProgressBarPosition.':0;" id="progress_'.$bannerGroupID.'"   class="progress" ></div>'; 
    }

    echo '</div>';    //display controll nav / paging
     if($showPaging==1){
     echo '<div class="wa-rsp-pager" id="wa-rsp-pager-'.$bannerGroupID.'"></div>';
    }  
?>
<script>
(function($) {

//animation for next and prev
$('#wa_rs_relative_container_<?php echo $bannerGroupID; ?>')
    .hover(function() {
        $('#wa_rs_relative_container_<?php echo $bannerGroupID; ?> .wa_rs_prev').animate({ 'left' : '1.2%', 'opacity' : 1 }), 300;
        $('#wa_rs_relative_container_<?php echo $bannerGroupID; ?> .wa_rs_next').animate({ 'right' : '1.2%', 'opacity' : 1 }), 300;
    }, function() {
        $('#wa_rs_relative_container_<?php echo $bannerGroupID; ?> .wa_rs_prev').animate({ 'left' : 0, 'opacity' : 0 }), 'fast';
        $('#wa_rs_relative_container_<?php echo $bannerGroupID; ?> .wa_rs_next').animate({ 'right' : 0, 'opacity' : 0 }), 'fast';
    });

    })(jQuery);

/* progress bar cycle */
var progress = $wa('#progress_<?php echo $bannerGroupID;?>'),
    slideshow = $wa( '#wa-slideshow_<?php echo $bannerGroupID;?>' );

slideshow.on( 'cycle-initialized cycle-before', function( e, opts ) {
    progress.stop(true).css( 'width', 0 );
});

slideshow.on( 'cycle-initialized cycle-after', function( e, opts ) {
    if ( ! slideshow.is('.cycle-paused') )
        progress.animate({ width: '100%' }, opts.timeout, 'linear' );
});

slideshow.on( 'cycle-paused', function( e, opts ) {
   progress.stop(); 
});

slideshow.on( 'cycle-resumed', function( e, opts, timeoutRemaining ) {
    progress.animate({ width: '100%' }, timeoutRemaining, 'linear' );
});


</script>
<?php if($lightBox=='1'){ ?>
<script>
$wa('#wa-slideshow_<?php echo $bannerGroupID;?>').magnificPopup({
  delegate: 'a', // child items selector, by clicking on it popup will open
  type: 'image'
  // other options
});
</script>
<?php
}
      }
    } 
  }
}
}
?>
