<?php
/**
 * @category    Trmmarketing
 * @package     Trmmarketing_Promotionalpopup
 * @copyright   Copyright (c) 2015 TRM Marketing LLC
 * @license     http://www.trm-marketing.com/solutions/license/TRM-Marketing-Standard-License-Agreement.html
 */  
			
			$popupModalClickClose = Mage::getStoreConfig('trmpopupconfig/trmpopupdesign_group/popupmodalclickclose',Mage::app()->getStore());
			$popupModalColor = Mage::getStoreConfig('trmpopupconfig/trmpopupdesign_group/popupmodalcolor',Mage::app()->getStore());
			$popupModalOpacity = Mage::getStoreConfig('trmpopupconfig/trmpopupdesign_group/popupmodalopacity',Mage::app()->getStore());
			$popupModalInDuration = Mage::getStoreConfig('trmpopupconfig/trmpopupdesign_group/popupmodalinduration',Mage::app()->getStore());
			$popupModalOutDuration = Mage::getStoreConfig('trmpopupconfig/trmpopupdesign_group/popupmodaloutduration',Mage::app()->getStore());
			
			$exitPopupInitDelay = Mage::getStoreConfig('trmpopupconfig/trmexitpopup_group/initdelay',Mage::app()->getStore());
			
			$arrParams = $this->getRequest()->getParams();
			
			// Google Analytics Params
			$popupSendToAnalytics = Mage::getStoreConfig('trmpopupconfig/trmpopuptracking_group/trackingoptions',Mage::app()->getStore()); 
			$gaEventCategory = Mage::getStoreConfig('trmpopupconfig/trmpopuptracking_group/eventcategory',Mage::app()->getStore());
			$gaViewEventAction = Mage::getStoreConfig('trmpopupconfig/trmpopuptracking_group/vieweventaction',Mage::app()->getStore()); 
			$gaConversionEventAction = Mage::getStoreConfig('trmpopupconfig/trmpopuptracking_group/conversioneventaction',Mage::app()->getStore()); 
			
			?>
            
			<?php $cookieConfig = Mage::getSingleton('core/cookie'); ?>
			<script>
			
		var excludedbrowsers = "<?php echo Mage::getStoreConfig('trmpopupconfig/trmpopup_group/excludebrowsers',Mage::app()->getStore()); ?>";
		var previewid = "<?php if(isset($arrParams['promotionalpopup_id'])) echo $arrParams['promotionalpopup_id']; ?>";	
		var modalcolor = "<?php if($popupModalColor): echo $popupModalColor; else: echo '#FFFFFF'; endif; ?>";
		var modalopacity = <?php if($popupModalOpacity): echo $popupModalOpacity; else: echo 0.5; endif; ?>;
		var fadeoutduration = <?php if (!$popupModalOutDuration == ""): echo $popupModalOutDuration; else: echo '.5'; endif; ?>;
		var fadeinduration = <?php if (!$popupModalInDuration == ""): echo $popupModalInDuration; else: echo '.5'; endif; ?>;
		var modalclickclose = <?php echo $popupModalClickClose; ?>;
		var loadpopupurl = "<?php echo $this->getUrl('promotionalpopup/index/loadpopup', array('_forced_secure' => $this->getRequest()->isSecure())) ?>";
		var viewpopupurl = "<?php echo $this->getUrl('promotionalpopup/index/view', array('_forced_secure' => $this->getRequest()->isSecure())) ?>";
		var conversionpopupurl = "<?php echo $this->getUrl('promotionalpopup/index/conversion', array('_forced_secure' => $this->getRequest()->isSecure())) ?>";
		var basemediaurl = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>";
		
		var disablepopupbelow = "<?php echo Mage::getStoreConfig('trmpopupconfig/trmpopup_group/disabledimension',Mage::app()->getStore()); ?>";
		var popupcookieconfigpath = "<?php echo $cookieConfig->getPath(); ?>";
		
		var popupgaeventcategory = "<?php echo $gaEventCategory; ?>";
		var popupgavieweventaction = "<?php echo $gaViewEventAction; ?>";
		var popupgaconversioneventaction = "<?php echo $gaConversionEventAction; ?>";
		var popupSendToAnalytics = "<?php echo $popupSendToAnalytics; ?>";
		
		initExitPopupTimer(<?php if($exitPopupInitDelay == ""): echo 5000; else: echo $exitPopupInitDelay; endif; ?>)
		
		</script>
            
            <div id="popupstyles"> </div>
            <div id="magentoPopupContainer"><!-- TRM Marketing Promotional Pop-ups ver 3.5.7 --></div>
            
            